name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ahmed-abdisalaam-ahmed
          outputs: dist/snake.svg
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Snake"
          add: "dist/snake.svg"
